### ISSUE TITLE
Any chance for TypeScript type definitions?

### ISSUE THREAD

**Issue by omaishar** [tandrewnichols/indefinite#12]

**Comment by tandrewnichols** [comment]
I don't personally use typescript, so I'm not _super_ excited about maintaining that, BUT the inputs and outputs should be more or less stable now (barring adding additional options I suppose), so I wouldn't reject a pull request to that effect (but it's also unlikely I'd care enough to do the work myself).

**Comment by omaishar** [comment]
I went ahead and added a pull request for type definitions for you package.
I hope you don't mind.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33207

**Comment by tandrewnichols** [comment]
Ok with me. I've not done typescript definitions before. Is there something that then needs to be added to this repo too?

**Comment by omaishar** [comment]
Here you go:
https://www.npmjs.com/package/@types/indefinite

**Comment by tandrewnichols** [comment]
Do I need to add that as a dependency? Or is that on the consumer?

**Comment by omaishar** [comment]
It's something the user should add if he uses type script. Nothing is required on your side.

**Comment by tandrewnichols** [comment]
Cool, thanks for taking that on.
