### ISSUE TITLE
Handle joined words LikeThis

### ISSUE THREAD

**Issue by mrseanryan** [tandrewnichols/indefinite#16]
In some applications we have joined words `LikeThis`.

`indefinite` cannot currently handle irregular cases like: `UserRole` or `userRole`.

It would be nice to add support for such joined words - maybe use library [decamelize](https://www.npmjs.com/package/decamelize) ?

**Comment by mrseanryan** [comment]
Let me know if that sounds useful. I could open a PR?

**Comment by tandrewnichols** [comment]
So what should it do? I'm unsure if you're saying it should return "a UserRole" or . . . maybe "a user role"? (The decamelize suggestion suggests the latter). I'm not against this; I think I just don't understand the request fully. But maybe a PR will make it clear.

**Comment by mrseanryan** [comment]
hi - I would expect:

`UserRole` -> `a UserRole`

(so the decamelization only happens internally).

**Comment by tandrewnichols** [comment]
I see. That probably does make sense then.

**Comment by mrseanryan** [comment]
Ok :) I will open a PR in next few days.

**Comment by mrseanryan** [comment]
Hi again

On second thoughts, I don't think this is a good idea. There are so many other cases, like snake case or hyphenated words etc. 

I think for such cases people can use other libraries in combination with this one. 

Else this library will get bigger and bigger :) 

What do you think?

**Comment by tandrewnichols** [comment]
Yeah, that makes sense. Thanks.
