### ISSUE TITLE
Add Utah to irregular words list

### ISSUE THREAD

**Issue by joshlikesyou** [tandrewnichols/indefinite#18]
Hi there, could you please add "Utah" to the irregular word list?
Thanks!

**Comment by tandrewnichols** [comment]
Yes (because "A Utah man" is correct), but also . . . is there an adjective form of that? Like "A Utahnian"?

**Comment by joshlikesyou** [comment]
Sorry didn't realize you were waiting for a response. It does seem like you could use a Utahn as an adjective to describe someone from Utah. However it does seem like it's common just use the name of the state in the same way that you would say California Condor or Florida Oranges.

**Comment by tandrewnichols** [comment]
I know I've definitely said "A Michigander" before. It doesn't hurt to put it in. Mostly I just wasn't sure what the definitive name was for someone from Utah.

**Comment by tandrewnichols** [comment]
Published as v2.3.1
