### ISSUE TITLE
the lib does not work when included in older browsers

### ISSUE THREAD

**Issue by emilos** [tandrewnichols/indefinite#4]
Hey,

thanks for the lib!

We tried to use it in an internal project which unfortunately needs to support some old browsers like IE10 without a big success.

To fix that I could contribute and add rollup + babel to create a transpiled version that could be accessed like:

```js
import indefinite from 'indefinite/dist/legacy'
```

If that's fine just let me know :)

**Comment by tandrewnichols** [comment]
I've never used rollup. I'm currently generating the primary dist files with webpack, which I know is overkill for a library, so I'd be curious to see what this looks like. If we do go that route, I'd probably just want to use _only_ rollup or _only_ webpack. Whichever is easiest to maintain multiple build targets with, cause I actually think it would be nice to package other module formats, like amd, under dist as well.

Out of curiosity, what issues are you seeing? I didn't specifically optimize for any particular browser target, but I would've thought anything supporting es5 would be okay.

**Comment by emilos** [comment]
@tandrewnichols thanks for the quick reply

It was one of those `silent` IE errors which do not show up in the console.

https://github.com/tandrewnichols/indefinite/pull/5
