### ISSUE TITLE
Missing release for 2.4.3

### ISSUE THREAD

**Issue by katerberg** [tandrewnichols/indefinite#63]
Looks like you bumped versions but didn't add a release for it. Looks like just dependency bumps, but it would be nice to confirm that.

**Comment by tandrewnichols** [comment]
Oh, I misread this. 2.4.3 _is_ published on npm, just not in the releases section. I will have to get to that later, as work is crazy right now. There is nothing special in 2.4.3. It's literally just a bunch of bot PRs to update dependencies.

**Comment by tandrewnichols** [comment]
Published: https://github.com/tandrewnichols/indefinite/releases/tag/v2.4.3
