### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by travishorn** [tandrewnichols/indefinite#9]
How about support for numbers?

For example, 

    `You rolled ${indefinite(82)}.`

yields "You rolled a 82." when it should yield "You rolled an 82."

**Comment by travishorn** [comment]
I thought about this further, and I've come up with some basic rules.

The indefinite article for all numbers is "a" **except**...

- 11
- 18
- Every number that starts with 8

Then there's these two interesting cases:

- 1100-1199, but only if pronouncing it eleven-hundred, eleven-oh-one, etc
- 1800-1899, but only if pronouncing it eighteen-hundred, eighteen forty-five, etc.

Most English speakers would read "**An** 1892 newspaper contains a story of..."
But in another context, the same number would read "**A** 1,892 year-old artifact was found..."

**Comment by tandrewnichols** [comment]
Sorry for the delay, we just had a baby, so I've been preoccupied. The first cases are straight-forward enough, but I don't know how we could know programmatically which is right in the last two cases. I'd probably default to using "a" because that simplifies the logic (only need to check if the number starts with 8 instead of whether it falls in a range).

**Comment by travishorn** [comment]
Congratulations on the baby, and no need to apologize. It was just a suggestion. IMO, you should add support for this only if and when you (or someone else with the skills) feel like it.

**Comment by tandrewnichols** [comment]
I don't object to adding it. I think it makes sense. It's just a question of the best way to do so.

**Comment by travishorn** [comment]
I think it makes sense to default to "a" but add an option if the number is typically read as, for example, eighteen-hundred.

You're correct, naming it something to do with "year" wouldn't work. I did a bunch of Googling but couldn't find any existing terminology for this phenomenon. I might call it "number grouping" or something like that?

**Comment by tandrewnichols** [comment]
Let's keep thinking about it. I don't have time to work it just yet anyway.

**Comment by tandrewnichols** [comment]
I've opened #10 to support this, but I'll wait a bit to see if you've got any feedback. If you want to take it for spin, you can install the `numbers` branch to see if all the edge cases are covered. (There was a lot more complexity than I expected with the logic here cause numbers like 110 and 180 should still get "a".)

**Comment by tandrewnichols** [comment]
Published as v2.2.0
